name: Build Latest Docker Image

defaults:
  run:
    working-directory: ./apps/server

on:
  pull_request:
      types: [opened, synchronize, reopened, closed]
      branches:
        - final

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build -t synbiosuite/seqimprove-api:latest .
