name: Deploy Latest Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  latest:
    name: Build and Deploy Latest Frontend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -f apps/web/Dockerfile -t synbiosuite/seqimprove-web:latest .
    
    - name: Login to DockerHub
      run: |
        docker login -u ${{ secrets.SYNBIOSUITE_DOCKER_USERNAME }} -p ${{ secrets.SYNBIOSUITE_DOCKER_PASSWORD }}
    
    - name: Push to DockerHub
      run: |
        docker push synbiosuite/seqimprove-web:latest

  latest-backend:
    name: Build and Deploy Latest Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/server

    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: |
        docker build -t synbiosuite/seqimprove-api:latest .
    
    - name: Login to DockerHub
      run: |
        docker login -u ${{ secrets.SYNBIOSUITE_DOCKER_USERNAME }} -p ${{ secrets.SYNBIOSUITE_DOCKER_PASSWORD }}
    
    - name: Push to DockerHub
      run: |
        docker push synbiosuite/seqimprove-api:latest
