name: Deploy Release Images

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    name: Build and Deploy Release Frontend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Extract version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Build Docker image
      run: |
        docker build -f apps/web/Dockerfile -t synbiosuite/seqimprove-web:${{ steps.version.outputs.VERSION }} -t synbiosuite/seqimprove-web:latest .
    
    - name: Login to DockerHub
      run: |
        docker login -u ${{ secrets.SYNBIOSUITE_DOCKER_USERNAME }} -p ${{ secrets.SYNBIOSUITE_DOCKER_PASSWORD }}
    
    - name: Push to DockerHub
      run: |
        docker push synbiosuite/seqimprove-web:${{ steps.version.outputs.VERSION }}
        docker push synbiosuite/seqimprove-web:latest

  release-backend:
    name: Build and Deploy Release Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/server

    steps:
    - uses: actions/checkout@v4
    
    - name: Extract version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Build Docker image
      run: |
        docker build -t synbiosuite/seqimprove-api:${{ steps.version.outputs.VERSION }} .
        docker build -t synbiosuite/seqimprove-api:latest .
    
    - name: Login to DockerHub
      run: |
        docker login -u ${{ secrets.SYNBIOSUITE_DOCKER_USERNAME }} -p ${{ secrets.SYNBIOSUITE_DOCKER_PASSWORD }}
    
    - name: Push to DockerHub
      run: |
        docker push synbiosuite/seqimprove-api:${{ steps.version.outputs.VERSION }}
        docker push synbiosuite/seqimprove-api:latest